
package your.domain.data;

import org.easydata.model.EasyPojo;


/**
 * This class has been generated by the EasyData library.
 * DO NOT MODIFY this class manually.
 * 
 */
public class Address
    extends EasyPojo
{

    private String PublicId;
    private String HouseNumber;
    private String Street;
    private String City;

    /**
     * Returns the PublicId.
     * 
     * @return
     *     PublicId
     */
    public String getPublicId() {
        return PublicId;
    }

    /**
     * Set the PublicId.
     * 
     * @param PublicId
     *     the new PublicId
     */
    public void setPublicId(String PublicId) {
        this.PublicId = PublicId;
    }

    /**
     * Returns the HouseNumber.
     * 
     * @return
     *     HouseNumber
     */
    public String getHouseNumber() {
        return HouseNumber;
    }

    /**
     * Set the HouseNumber.
     * 
     * @param HouseNumber
     *     the new HouseNumber
     */
    public void setHouseNumber(String HouseNumber) {
        this.HouseNumber = HouseNumber;
    }

    /**
     * Returns the Street.
     * 
     * @return
     *     Street
     */
    public String getStreet() {
        return Street;
    }

    /**
     * Set the Street.
     * 
     * @param Street
     *     the new Street
     */
    public void setStreet(String Street) {
        this.Street = Street;
    }

    /**
     * Returns the City.
     * 
     * @return
     *     City
     */
    public String getCity() {
        return City;
    }

    /**
     * Set the City.
     * 
     * @param City
     *     the new City
     */
    public void setCity(String City) {
        this.City = City;
    }

    public String getKeyValue() {
        return this.PublicId;
    }

}
