
package your.domain.data;

import org.easydata.model.EasyPojo;


/**
 * This class has been generated by the EasyData library.
 * DO NOT MODIFY this class manually.
 * 
 */
public class Employee
    extends EasyPojo
{

    private String PublicId;
    private String NoOfChildren;
    private String AddressId;
    private String LastName;
    private String BossId;
    private String FirstName;
    private String DateOfBirth;

    /**
     * Returns the PublicId.
     * 
     * @return
     *     PublicId
     */
    public String getPublicId() {
        return PublicId;
    }

    /**
     * Set the PublicId.
     * 
     * @param PublicId
     *     the new PublicId
     */
    public void setPublicId(String PublicId) {
        this.PublicId = PublicId;
    }

    /**
     * Returns the NoOfChildren.
     * 
     * @return
     *     NoOfChildren
     */
    public String getNoOfChildren() {
        return NoOfChildren;
    }

    /**
     * Set the NoOfChildren.
     * 
     * @param NoOfChildren
     *     the new NoOfChildren
     */
    public void setNoOfChildren(String NoOfChildren) {
        this.NoOfChildren = NoOfChildren;
    }

    /**
     * Returns the AddressId.
     * 
     * @return
     *     AddressId
     */
    public String getAddressId() {
        return AddressId;
    }

    /**
     * Set the AddressId.
     * 
     * @param AddressId
     *     the new AddressId
     */
    public void setAddressId(String AddressId) {
        this.AddressId = AddressId;
    }

    /**
     * Returns the LastName.
     * 
     * @return
     *     LastName
     */
    public String getLastName() {
        return LastName;
    }

    /**
     * Set the LastName.
     * 
     * @param LastName
     *     the new LastName
     */
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    /**
     * Returns the BossId.
     * 
     * @return
     *     BossId
     */
    public String getBossId() {
        return BossId;
    }

    /**
     * Set the BossId.
     * 
     * @param BossId
     *     the new BossId
     */
    public void setBossId(String BossId) {
        this.BossId = BossId;
    }

    /**
     * Returns the FirstName.
     * 
     * @return
     *     FirstName
     */
    public String getFirstName() {
        return FirstName;
    }

    /**
     * Set the FirstName.
     * 
     * @param FirstName
     *     the new FirstName
     */
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    /**
     * Returns the DateOfBirth.
     * 
     * @return
     *     DateOfBirth
     */
    public String getDateOfBirth() {
        return DateOfBirth;
    }

    /**
     * Set the DateOfBirth.
     * 
     * @param DateOfBirth
     *     the new DateOfBirth
     */
    public void setDateOfBirth(String DateOfBirth) {
        this.DateOfBirth = DateOfBirth;
    }

    public String getKeyValue() {
        return this.PublicId;
    }

}
