
package your.domain.data;

import java.io.IOException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import org.easydata.model.EasyRepository;


/**
 * This class has been generated by the EasyData library.
 * DO NOT MODIFY this class manually.
 * 
 */
public class Repositories {

    private static Map<Class<?> , EasyRepository<?>> REPOS = new HashMap<Class<?> , EasyRepository<?>>();

    public static void init(String path)
        throws IOException
    {
        REPOS.put(Employees.class, new Employees());
        REPOS.put(Bosses.class, new Bosses());
        REPOS.put(Addresses.class, new Addresses());
        Iterator<EasyRepository<?>> iter = REPOS.values().iterator();
        while (iter.hasNext()) {
            EasyRepository<?> repo = iter.next();
            repo.init(path);
        }
    }

    public static<T extends EasyRepository<?> >T get(Class<T> type) {
        return type.cast(REPOS.get(type));
    }

}
