package org.easydata.generator;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;

import org.apache.commons.csv.CSVRecord;
import org.easydata.access.EasyCSVRepository;
import org.easydata.access.EasyRepository;
import org.easydata.model.EasyClass;
import org.easydata.model.EasyField;
import org.easydata.model.EasyModel;
import org.easydata.model.EasyRelation;
import org.easydata.model.EasyType;
import org.easydata.util.EasyLogger;

import com.sun.codemodel.JClass;
import com.sun.codemodel.JClassAlreadyExistsException;
import com.sun.codemodel.JCodeModel;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JExpr;
import com.sun.codemodel.JExpression;
import com.sun.codemodel.JFieldVar;
import com.sun.codemodel.JMethod;
import com.sun.codemodel.JMod;
import com.sun.codemodel.JMods;
import com.sun.codemodel.JPackage;
import com.sun.codemodel.JType;
import com.sun.codemodel.JVar;
import com.sun.codemodel.JWhileLoop;

import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.Object2ObjectMap;

public class EasyRepositoryGenerator extends EasyCodeGenerator {

	private static final String _MODEL_PACKAGE_NAME = "your.domain.data";
	private static final String _REPOSITORIES_CLASS = "Repositories";
	
	private static final Comparator<EasyField> _FIELD_INDEX_COMP = new Comparator<EasyField>() {
    	public int compare(EasyField one, EasyField two) {
    		return one.index - two.index;
    	}
    };
	
	private JCodeModel _cm = null;
	private EasyModel _em = null;
	
	@Override
	public void generateCode(EasyModel model, JCodeModel codeModel) {

		this._cm = codeModel;
		this._em = model;
		
		JPackage pkg = codeModel._package(_MODEL_PACKAGE_NAME);
		
		try {
			
			addRepositoriesClass();
			
			for (EasyClass clazz : model.classes) {
				addRepositoryClass(clazz, pkg);
			}
			
			addRepositoriesInitMethod();
			
		} catch (JClassAlreadyExistsException jcae) {}
		
	}
	
	/**
	 * Creates a repository class for every class in the model.
	 * 
	 * @param clazz
	 * @param pkg
	 * @throws JClassAlreadyExistsException
	 */
	private void addRepositoryClass(EasyClass clazz, JPackage pkg) 
			throws JClassAlreadyExistsException {

		String name = clazz.targetClassName + getPluralSuffix(clazz);

		JClass superClass = this._cm.ref(EasyCSVRepository.class)
				.narrow(this._cm.ref(clazz.targetClassName));
		
		JDefinedClass jc = pkg._class(name);
		jc._extends(superClass);
		jc.javadoc().add("This class has been generated by the EasyData library.\n");
		jc.javadoc().add("DO NOT MODIFY this class manually.");
		
		// add main repository
		JFieldVar jField = addMainRepository(clazz, jc, name);
		
		// create indices for other objects which have a one to many to this one
		for (EasyRelation relation : clazz.getManyToOneRelations()) {
			createReferenceIndex(clazz, relation, jc);
		}
		
		// getById method
		addGetByIdMethod(clazz, jc, jField);

		// create method to get objects from other repos which the class managed
		// by this repo is managing
		for (EasyRelation relation : clazz.getOneToManyRelations()) {
			createGetter(clazz, relation, jc);
		}
		
		// createFrom method
		addCreateFromMethod(clazz, jc);
		
		// add method
		addAddMethod(clazz, jc, jField);
		
		// getInputFileName method
		addGetInputFileNameMethod(clazz, jc);
		
		// size method
		addSizeMethod(clazz, jc, jField);
		
		// populateReferenceIndices method
		addPopulateReferenceIndicesMethod(clazz, jc);
		
	}

	private void createGetter(EasyClass clazz, EasyRelation relation, JDefinedClass jc) {
		
		// TODO: Implement
		EasyLogger.getEasyLogger().warn("EasyRepositoryGenerator#createGetter has not been implemented yet!");
		String repoName = clazz.targetClassName + getPluralSuffix(clazz);
		
		JDefinedClass repos = this._cm._package(_MODEL_PACKAGE_NAME)._getClass(repoName);
		
		String name = "get" + clazz.targetClassName + "By" + relation.getTo() + "Id";
		JMethod getByParentID = repos.method(JMod.PUBLIC | JMod.STATIC, this._cm.ref(clazz.targetClassName), name);
		getByParentID.body()._return(JExpr._null());
		
	}
	
	private JFieldVar addMainRepository(EasyClass clazz, JDefinedClass jc, String name) {
		
		// map holding the single items
		JType jtype = this._cm.ref(Object2ObjectMap.class).narrow(
				this._cm.ref(String.class),
				this._cm.ref(clazz.targetClassName)
		);
		
		JClass jtypeImpl = this._cm.ref(Object2ObjectOpenHashMap.class).narrow(
				this._cm.ref(String.class),
				this._cm.ref(clazz.targetClassName)
		);
		
		JFieldVar jField = jc.field(JMod.PRIVATE, jtype, name);
		jField.init(JExpr._new(jtypeImpl));
		
		return jField;
		
	}
	
	private void createReferenceIndex(EasyClass clazz, EasyRelation relation, JDefinedClass jc) {
		
		String name = clazz.targetClassName + getPluralSuffix(clazz);
		
		JType jtype = this._cm.ref(Object2ObjectMap.class).narrow(
				this._cm.ref(String.class),
				this._cm.ref(java.util.HashSet.class).narrow(String.class)
		);
		
		JClass jtypeImpl = this._cm.ref(Object2ObjectOpenHashMap.class).narrow(
				this._cm.ref(String.class),
				this._cm.ref(java.util.HashSet.class).narrow(String.class)
		);
		
		JFieldVar jField = jc.field(JMod.PRIVATE, jtype, name + "By" + relation.getTo());
		jField.init(JExpr._new(jtypeImpl));
		
	} 
	
	private void addPopulateReferenceIndicesMethod(EasyClass clazz, JDefinedClass jc) {
		
		JMethod populateReferenceIndices = jc.method(JMod.PROTECTED, this._cm.VOID, "populateReferenceIndices");
		
	}
	
	/**
	 * Creates the "createFrom" interface method.
	 * 
	 * @param clazz
	 * @param jc
	 */
	private void addCreateFromMethod(EasyClass clazz, JDefinedClass jc) {
		
		JMethod createFrom = jc.method(JMod.PUBLIC, this._cm.ref(clazz.targetClassName), "createFrom");
		createFrom.param(CSVRecord.class, "record");
		createFrom._throws(java.text.ParseException.class);
		
		JVar dateFormat = null;
        
        if (clazz.hasDateField()) {
        	 
        	dateFormat = createFrom.body().decl(this._cm.ref(SimpleDateFormat.class), "sdf");
			dateFormat.init(JExpr._new(this._cm.ref(SimpleDateFormat.class)).arg("dd/MM/yy"));	
        	
        }
        
        JClass createFromResultType = this._cm.ref(clazz.targetClassName);
        JVar createFromResult = createFrom.body().decl(createFromResultType, clazz.targetClassName.toLowerCase());
        createFromResult.init(JExpr._new(this._cm.ref(clazz.targetClassName)));
        
        List<EasyField> fields = new ArrayList<EasyField>(clazz.fields);
        Collections.sort(fields, _FIELD_INDEX_COMP);
        
		for (EasyField field : fields) {
		
			JExpression p2 = JExpr.direct("record.get(" + field.index + ")");
			
			if (field.type.equals(EasyType.TEXT.getType())) {
				createFrom.body().add(createFromResult.invoke("set" + field.targetFieldName).arg(p2));
			} else if (field.type.equals(EasyType.DATE.getType())) {
				createFrom.body().add(
						createFromResult.invoke("set" + field.targetFieldName).arg(
								dateFormat.invoke("parse").arg(p2)
							));
			} else if (field.type.equals(EasyType.INTEGER.getType())) {
				createFrom.body().add(
						createFromResult.invoke("set" + field.targetFieldName).arg(
								this._cm.ref(Integer.class).staticInvoke("valueOf").arg(p2)
							));
			}
			
		}
		
		createFrom.body()._return(createFromResult);
		
	}
	
	/**
	 * Creates the "add" interface method.
	 * 
	 * @param clazz
	 * @param definedClass
	 * @param repoMap
	 */
	private void addAddMethod(EasyClass clazz, JDefinedClass definedClass, JFieldVar repoMap) {
		
		JMethod addMethod = definedClass.method(JMod.PUBLIC, this._cm.BOOLEAN, "add");
		addMethod._throws(IllegalArgumentException.class);
		JVar param = addMethod.param(this._cm.ref(clazz.targetClassName), "item");
		
		addMethod.body()
			._if(param.eq(JExpr._null()))
			._then()
			._throw(JExpr._new(this._cm.ref(IllegalArgumentException.class)).arg("item cannot be null!"));
		
		addMethod.body()
			._if(param.invoke("getKeyValue").eq(JExpr._null()).cor(param.invoke("getKeyValue").invoke("isEmpty")))
			._then()
			._throw(JExpr._new(this._cm.ref(IllegalArgumentException.class)).arg("item key value cannot be null or empty!"));
		
		addMethod.body()
			._if(repoMap.invoke("containsKey").arg(param.invoke("getKeyValue")).not())
			._then()
				.add(repoMap.invoke("put").arg(param.invoke("getKeyValue")).arg(param))
				._return(JExpr.TRUE);
					
		addMethod.body()._return(JExpr.FALSE);
		
	}
	
	private void addGetByIdMethod(EasyClass clazz, JDefinedClass jc, JFieldVar map) {
		
		JMethod getById = jc.method(JMod.PUBLIC, this._cm.ref(clazz.targetClassName), "getById");
		JVar param = getById.param(String.class, "id");
		getById.body()._return(JExpr._this().ref(map).invoke("get").arg(param));
		
	}
	
	private void addGetInputFileNameMethod(EasyClass clazz, JDefinedClass jc) {
		
		JMethod getInputFileName = jc.method(JMod.PUBLIC, String.class, "getInputFileName");
		getInputFileName.body()._return(JExpr.lit(clazz.fileName));
		
	}
	
	private void addSizeMethod(EasyClass clazz, JDefinedClass jc, JFieldVar map) {
		
		JMethod size = jc.method(JMod.PUBLIC, this._cm.INT, "size");
		size.body()._return(map.invoke("size"));
		
	}
	
	private void addRepositoriesClass() throws JClassAlreadyExistsException {
		
		JDefinedClass repos = this._cm._package(_MODEL_PACKAGE_NAME)._class(_REPOSITORIES_CLASS);
		repos.javadoc().add("This class has been generated by the EasyData library.\n");
		repos.javadoc().add("DO NOT MODIFY this class manually.");
		
		JType jtype = this._cm.ref(java.util.Map.class).narrow(
				this._cm.ref(Class.class).narrow(this._cm.wildcard()),
				this._cm.ref(EasyRepository.class).narrow(this._cm.wildcard())
		);
		
		JClass jtypeImpl = this._cm.ref(java.util.HashMap.class).narrow(
				this._cm.ref(Class.class).narrow(this._cm.wildcard()),
				this._cm.ref(EasyRepository.class).narrow(this._cm.wildcard())
		);
		
		JFieldVar jField = repos.field(JMod.PRIVATE | JMod.STATIC, jtype, "REPOS");
		jField.init(JExpr._new(jtypeImpl));
		
		// get method
		JType genericType = this._cm.directClass("T");
		JMethod get = repos.method(JMod.PUBLIC | JMod.STATIC, genericType, "get");
		
		JClass genericClass = this._cm.ref(EasyRepository.class).narrow(this._cm.wildcard());
		
		get.generify("T", genericClass);
        JClass parameterType = this._cm.ref(Class.class).narrow(genericType);
        JVar getParam = get.param(parameterType, "type");
        get.body()._return(getParam.invoke("cast").arg(JExpr.ref("REPOS").invoke("get").arg(getParam)));
		
	}
	
	private void addRepositoriesInitMethod() {
		
		JDefinedClass repos = this._cm._package(_MODEL_PACKAGE_NAME)._getClass(_REPOSITORIES_CLASS);
		
		// init method
		JMethod init = repos.method(JMod.PUBLIC | JMod.STATIC, this._cm.VOID, "init");
		JVar param = init.param(String.class, "path");
		init._throws(IOException.class);
		
		for (EasyClass clazz : this._em.classes) {
		
			String name = clazz.targetClassName + getPluralSuffix(clazz);
			init.body().add(JExpr.ref("REPOS").invoke("put")
					.arg(JExpr.dotclass(this._cm.ref(name)))
					.arg(JExpr._new(this._cm.ref(name))));
			
		}
		
		JClass repo = this._cm.ref(Iterator.class).narrow(this._cm.ref(EasyRepository.class).narrow(this._cm.wildcard()));;
		init.body().decl(repo, "iter", JExpr.ref("REPOS").invoke("values").invoke("iterator"));
		
		JWhileLoop loop = init.body()._while(JExpr.ref("iter").invoke("hasNext"));
		JVar repoVar = loop.body().decl(this._cm.ref(EasyRepository.class).narrow(this._cm.wildcard()), "repo", JExpr.ref("iter").invoke("next"));
		loop.body().add(repoVar.invoke("init").arg(param));
	}
	
	private String getPluralSuffix(EasyClass clazz) {
		String suffix = "s";
		if (clazz.targetClassName.endsWith("s")) {
			suffix = "es";
		}
		return suffix;
	}

}
